### ISSUE TITLE
Licensing and project status?

### ISSUE THREAD

**Issue by boqwxp** [tdb-alcorn/firrtl-parser#1]
Hi,

This looks like it might be useful as part of [Yosys](https://github.com/YosysHQ/yosys).  Can you please clarify under what terms you're willing to license this (ISC license would be ideal)?  Also, what is the status of the project?  Does it work?  How much of the (I assume LoFIRRTL) spec does it support?

Your participation in the discussion in [this issue](https://github.com/YosysHQ/yosys/issues/2004) would be very welcome.

Thanks in advance!

**Comment by boqwxp** [comment]
It looks like we'll be moving forward with integrating [this](https://github.com/chipsalliance/tree-sitter-firrtl/) instead.  Your input would still be welcome, though!

**Comment by tdb-alcorn** [comment]
I see you're working on a Firrtl frontend for Yosys [here](https://github.com/boqwxp/yosys/tree/frontend-firrtl). Awesome! My end goal with this project was to integrate it into Yosys, but I figured out some workarounds that negated the need for me to finish this.

Feel free to crib anything you want from this project. I'll update the license to ISC.

**Comment by boqwxp** [comment]
Great, thanks!
